name: ci

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, closed]

permissions:
  contents: read

jobs:
  coverage:
    name: coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          fetch-depth: 100
      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          go-version: '1.26.3'
          check-latest: true
      - name: Run coverage
        working-directory: ./pkg
        run: go test -coverprofile=coverage.out -covermode=count
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@e79a6962e0d4c0c17b229090214935d2e33f8354 # v6
