name: ci

on:
  push:
    branches: ['*']
    tags: ['v*']
  pull_request:
    branches: ['*']

jobs:
  coverage:
    name: coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 100
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.18'
          check-latest: true
      - name: Run coverage
        run: go test -coverprofile=coverage.out -covermode=count
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3