name: govulncheck

on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: '23 9 * * 3'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  govulncheck:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dir: ['pkg', 'cmd/zstdseek']
    env:
      GOTOOLCHAIN: local
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v6
        with:
          go-version: stable
          check-latest: true
          cache-dependency-path: ${{ matrix.dir }}/go.sum
      - name: Install govulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@latest
      - name: Scan for vulnerabilities (${{ matrix.dir }})
        working-directory: ./${{ matrix.dir }}
        run: govulncheck -test ./...
